// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_yucNAorddZVc-z8PYLlVe0WwfZMM8M',
    appId: '1:677255228952:web:629f2b4f5df5ab0b615d6d',
    messagingSenderId: '677255228952',
    projectId: 'pbljawara',
    authDomain: 'pbljawara.firebaseapp.com',
    storageBucket: 'pbljawara.firebasestorage.app',
    measurementId: 'G-BJH1MBDHLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIVFcSXlbkzVS8cZLQowiAoKwsdhDlCPk',
    appId: '1:677255228952:android:fd9341a1c783a139615d6d',
    messagingSenderId: '677255228952',
    projectId: 'pbljawara',
    storageBucket: 'pbljawara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zoNi7qedptztAte0ht2H10Hn4t6DAAM',
    appId: '1:677255228952:ios:589ab504f8d74af8615d6d',
    messagingSenderId: '677255228952',
    projectId: 'pbljawara',
    storageBucket: 'pbljawara.firebasestorage.app',
    iosBundleId: 'com.example.pblNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2zoNi7qedptztAte0ht2H10Hn4t6DAAM',
    appId: '1:677255228952:ios:589ab504f8d74af8615d6d',
    messagingSenderId: '677255228952',
    projectId: 'pbljawara',
    storageBucket: 'pbljawara.firebasestorage.app',
    iosBundleId: 'com.example.pblNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_yucNAorddZVc-z8PYLlVe0WwfZMM8M',
    appId: '1:677255228952:web:c6c0fd38b2971a41615d6d',
    messagingSenderId: '677255228952',
    projectId: 'pbljawara',
    authDomain: 'pbljawara.firebaseapp.com',
    storageBucket: 'pbljawara.firebasestorage.app',
    measurementId: 'G-25LYS8PTF2',
  );
}
